// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commandHandler.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SocialFollower struct {
	Youtube              int32    `protobuf:"varint,1,opt,name=youtube,proto3" json:"youtube,omitempty"`
	Twitter              int32    `protobuf:"varint,2,opt,name=twitter,proto3" json:"twitter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocialFollower) Reset()         { *m = SocialFollower{} }
func (m *SocialFollower) String() string { return proto.CompactTextString(m) }
func (*SocialFollower) ProtoMessage()    {}
func (*SocialFollower) Descriptor() ([]byte, []int) {
	return fileDescriptor_commandHandler_47167b30f9e02166, []int{0}
}
func (m *SocialFollower) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocialFollower.Unmarshal(m, b)
}
func (m *SocialFollower) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocialFollower.Marshal(b, m, deterministic)
}
func (dst *SocialFollower) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocialFollower.Merge(dst, src)
}
func (m *SocialFollower) XXX_Size() int {
	return xxx_messageInfo_SocialFollower.Size(m)
}
func (m *SocialFollower) XXX_DiscardUnknown() {
	xxx_messageInfo_SocialFollower.DiscardUnknown(m)
}

var xxx_messageInfo_SocialFollower proto.InternalMessageInfo

func (m *SocialFollower) GetYoutube() int32 {
	if m != nil {
		return m.Youtube
	}
	return 0
}

func (m *SocialFollower) GetTwitter() int32 {
	if m != nil {
		return m.Twitter
	}
	return 0
}

type Person struct {
	Name                 string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32           `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Socialfollower       *SocialFollower `protobuf:"bytes,3,opt,name=socialfollower,proto3" json:"socialfollower,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_commandHandler_47167b30f9e02166, []int{1}
}
func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (dst *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(dst, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetSocialfollower() *SocialFollower {
	if m != nil {
		return m.Socialfollower
	}
	return nil
}

type Population struct {
	People               *Person  `protobuf:"bytes,1,opt,name=people,proto3" json:"people,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Population) Reset()         { *m = Population{} }
func (m *Population) String() string { return proto.CompactTextString(m) }
func (*Population) ProtoMessage()    {}
func (*Population) Descriptor() ([]byte, []int) {
	return fileDescriptor_commandHandler_47167b30f9e02166, []int{2}
}
func (m *Population) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Population.Unmarshal(m, b)
}
func (m *Population) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Population.Marshal(b, m, deterministic)
}
func (dst *Population) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Population.Merge(dst, src)
}
func (m *Population) XXX_Size() int {
	return xxx_messageInfo_Population.Size(m)
}
func (m *Population) XXX_DiscardUnknown() {
	xxx_messageInfo_Population.DiscardUnknown(m)
}

var xxx_messageInfo_Population proto.InternalMessageInfo

func (m *Population) GetPeople() *Person {
	if m != nil {
		return m.People
	}
	return nil
}

func init() {
	proto.RegisterType((*SocialFollower)(nil), "main.socialFollower")
	proto.RegisterType((*Person)(nil), "main.person")
	proto.RegisterType((*Population)(nil), "main.population")
}

func init() {
	proto.RegisterFile("commandHandler.proto", fileDescriptor_commandHandler_47167b30f9e02166)
}

var fileDescriptor_commandHandler_47167b30f9e02166 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x31, 0x6f, 0x83, 0x30,
	0x14, 0x84, 0x45, 0xa1, 0x54, 0x7d, 0x54, 0x55, 0x65, 0x31, 0x78, 0x44, 0xa8, 0x03, 0x13, 0x03,
	0x5d, 0x3b, 0x46, 0x51, 0x66, 0xff, 0x03, 0x03, 0x4e, 0x64, 0xc9, 0xf6, 0xb3, 0x8c, 0x11, 0xca,
	0xbf, 0x8f, 0x8c, 0xcd, 0x90, 0x6c, 0x77, 0x3a, 0x9f, 0xbf, 0x7b, 0x50, 0x4f, 0xa8, 0x35, 0x37,
	0xf3, 0x85, 0x9b, 0x59, 0x09, 0xd7, 0x5b, 0x87, 0x1e, 0x49, 0xa1, 0xb9, 0x34, 0xed, 0x09, 0xbe,
	0x17, 0x9c, 0x24, 0x57, 0x67, 0x54, 0x0a, 0x37, 0xe1, 0x08, 0x85, 0x8f, 0x3b, 0xae, 0x7e, 0x1d,
	0x05, 0xcd, 0x9a, 0xac, 0x7b, 0x67, 0x87, 0x0d, 0x89, 0xdf, 0xa4, 0xf7, 0xc2, 0xd1, 0xb7, 0x98,
	0x24, 0xdb, 0x2a, 0x28, 0xad, 0x70, 0x0b, 0x1a, 0x42, 0xa0, 0x30, 0x5c, 0xc7, 0xea, 0x27, 0xdb,
	0x35, 0xf9, 0x81, 0x9c, 0xdf, 0x44, 0xea, 0x04, 0x49, 0xfe, 0x0f, 0xea, 0x35, 0x51, 0x69, 0xde,
	0x64, 0x5d, 0x35, 0xd4, 0x7d, 0x18, 0xd5, 0x3f, 0x2f, 0x62, 0x2f, 0x6f, 0xdb, 0x01, 0xc0, 0xa2,
	0x5d, 0x15, 0xf7, 0x12, 0x0d, 0xf9, 0x0d, 0x6c, 0xb4, 0x2a, 0x32, 0xab, 0xe1, 0x2b, 0xfe, 0x11,
	0xf7, 0xb0, 0x94, 0x8d, 0xe5, 0x7e, 0xf4, 0xdf, 0x23, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x20, 0x05,
	0xfb, 0x0c, 0x01, 0x00, 0x00,
}
